services:
  webserver:
    image: nginx:alpine
    container_name: dionii_webserver
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - database
    networks:
      - dionii_network

  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: dionii_php
    restart: unless-stopped
    volumes:
      - ./:/var/www/html
    environment:
      - DB_HOST=database
      - DB_PORT=3306
      - DB_DATABASE=${DB_DATABASE:-laravel}
      - DB_USERNAME=${DB_USERNAME:-laravel_user}
      - DB_PASSWORD=${DB_PASSWORD:-secret}
    depends_on:
      - database
    networks:
      - dionii_network

  database:
    image: mysql:8.0
    container_name: dionii_database
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: ${DB_DATABASE:-laravel}
      MYSQL_USER: ${DB_USERNAME:-laravel_user}
      MYSQL_PASSWORD: ${DB_PASSWORD:-secret}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-root_secret}
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - dionii_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: dionii_phpmyadmin
    restart: unless-stopped
    ports:
      - "8081:80"
    environment:
      PMA_HOST: database
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: ${DB_ROOT_PASSWORD:-root_secret}
      UPLOAD_LIMIT: 256M
    depends_on:
      - database
    networks:
      - dionii_network

networks:
  dionii_network:
    driver: bridge

volumes:
  db_data:
    driver: local
